#include-once
#include 'include\au3Irr2_Constants.au3'
#include 'include\au3Irr2_System.au3'
#include 'include\au3Irr2_KeyboardMouse.au3'
#include 'include\au3Irr2_FilingSystem.au3'
#include 'include\au3Irr2_2D.au3'
#include 'include\au3Irr2_Materials.au3'
#include 'include\au3Irr2_Scene.au3'
#include 'include\au3Irr2_Node.au3'
#include 'include\au3Irr2_Animation.au3'
#include 'include\au3Irr2_Collision.au3'
#include 'include\au3Irr2_Camera.au3'
#include 'include\au3Irr2_Lighting.au3'
#include 'include\au3Irr2_Terrain.au3'
#include 'include\au3Irr2_Particles.au3'
#include 'include\au3Irr2_GUI.au3'
